package com.corehive.backend.service;

import com.corehive.backend.model.Employee;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.time.LocalDate;
import java.util.List;
import java.util.Map;

@Service
public class HrEmployeeExcelService {

    public byte[] generateEmployeeExcel(Map<String, Object> data) {

        try (Workbook workbook = new XSSFWorkbook()) {

            Sheet sheet = workbook.createSheet("Employee Details");
            int rowIdx = 0;

            /* =========================
               META SECTION
            ========================= */
            rowIdx = createMetaRow(sheet, rowIdx, "Organization", data.get("organizationName"));
            rowIdx = createMetaRow(sheet, rowIdx, "Report Name", "Employee Master Report");
            rowIdx = createMetaRow(sheet, rowIdx, "Generated Date", LocalDate.now().toString());
            rowIdx = createMetaRow(sheet, rowIdx, "Generated By", "HR Admin");
            rowIdx = createMetaRow(sheet, rowIdx, "Total Employees", data.get("total"));
            rowIdx = createMetaRow(sheet, rowIdx, "Active Employees", data.get("active"));
            rowIdx = createMetaRow(sheet, rowIdx, "Inactive Employees", data.get("inactive"));

            rowIdx += 2; // spacing

            /* =========================
               TABLE HEADER
            ========================= */
            Row header = sheet.createRow(rowIdx++);
            String[] columns = {
                    "Employee Code", "First Name", "Last Name", "Email",
                    "Phone Number", "National ID", "Designation",
                    "Department Name", "Salary Type", "Basic Salary",
                    "Bank Account No", "Date of Joining", "Employment Status"
            };

            CellStyle headerStyle = createHeaderStyle(workbook);
            for (int i = 0; i < columns.length; i++) {
                Cell cell = header.createCell(i);
                cell.setCellValue(columns[i]);
                cell.setCellStyle(headerStyle);
                sheet.autoSizeColumn(i);
            }

            /* =========================
               TABLE BODY
            ========================= */
            List<Employee> employees =
                    (List<Employee>) data.get("employees");

            for (Employee e : employees) {
                Row row = sheet.createRow(rowIdx++);

                row.createCell(0).setCellValue(e.getEmployeeCode());
                row.createCell(1).setCellValue(e.getFirstName());
                row.createCell(2).setCellValue(e.getLastName());
                row.createCell(3).setCellValue(e.getEmail());
                row.createCell(4).setCellValue(e.getPhone());
                row.createCell(5).setCellValue(e.getNationalId());
                row.createCell(6).setCellValue(e.getDesignation());
                row.createCell(7).setCellValue(
                        e.getDepartment() != null ? e.getDepartment().getName() : "N/A"
                );
                row.createCell(8).setCellValue(e.getSalaryType().name());
                row.createCell(9).setCellValue(
                        e.getBasicSalary() != null ? e.getBasicSalary().doubleValue() : 0
                );
                row.createCell(10).setCellValue(e.getBankAccNo());
                row.createCell(11).setCellValue(
                        e.getDateOfJoining() != null ? e.getDateOfJoining().toString() : ""
                );
                row.createCell(12).setCellValue(
                        Boolean.TRUE.equals(e.getIsActive()) ? "Active" : "Inactive"
                );
            }

            ByteArrayOutputStream out = new ByteArrayOutputStream();
            workbook.write(out);
            return out.toByteArray();

        } catch (Exception e) {
            throw new RuntimeException("Excel generation failed", e);
        }
    }

    /* =========================
       HELPERS
    ========================= */
    private int createMetaRow(Sheet sheet, int rowIdx, String key, Object value) {
        Row row = sheet.createRow(rowIdx++);
        row.createCell(0).setCellValue(key);
        row.createCell(1).setCellValue(String.valueOf(value));
        return rowIdx;
    }

    private CellStyle createHeaderStyle(Workbook wb) {
        CellStyle style = wb.createCellStyle();
        Font font = wb.createFont();
        font.setBold(true);
        style.setFont(font);
        return style;
    }
}

