/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/feedback` | `/feedback`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/notices` | `/notices`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/support` | `/support`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/surveys` | `/surveys`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/attendance` | `/attendance`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/leave` | `/leave`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/more` | `/more`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/payslips` | `/payslips`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/profile/edit` | `/profile/edit`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/feedback` | `/feedback`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/notices` | `/notices`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/support` | `/support`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/surveys` | `/surveys`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/attendance` | `/attendance`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/leave` | `/leave`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/more` | `/more`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/payslips` | `/payslips`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/profile/edit` | `/profile/edit`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/feedback${`?${string}` | `#${string}` | ''}` | `/feedback${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/notices${`?${string}` | `#${string}` | ''}` | `/notices${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/support${`?${string}` | `#${string}` | ''}` | `/support${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/surveys${`?${string}` | `#${string}` | ''}` | `/surveys${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(tabs)'}/attendance${`?${string}` | `#${string}` | ''}` | `/attendance${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(tabs)'}/leave${`?${string}` | `#${string}` | ''}` | `/leave${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(tabs)'}/more${`?${string}` | `#${string}` | ''}` | `/more${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(tabs)'}/payslips${`?${string}` | `#${string}` | ''}` | `/payslips${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/profile/edit${`?${string}` | `#${string}` | ''}` | `/profile/edit${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/feedback` | `/feedback`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/notices` | `/notices`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/support` | `/support`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/surveys` | `/surveys`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/attendance` | `/attendance`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/leave` | `/leave`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/more` | `/more`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/payslips` | `/payslips`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/profile/edit` | `/profile/edit`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; };
    }
  }
}
